###############################################
# Modify all parameters related to servoing here
###############################################
ur_teleop_node:
  ros__parameters:
    servo_linear_scale: 0.1
    servo_angular_scale: 0.25
    servo_twist_smooth_factor: 0.25

    moveit_servo:
      ## Properties of outgoing commands
      publish_period: 0.01  # 1/Nominal publish rate [seconds]
      max_expected_latency: 0.1

      ## MoveIt properties
      move_group_name:  ur_manipulator_with_vg10  # Often 'manipulator' or 'arm'

      ## Topic names and properties of commands
      command_in_type: "speed_units" # "unitless"> in the range [-1:1], as if from joystick. "speed_units"> cmds are in m/s and rad/s
      status_topic: ~/status # Publish status to this topic
      command_out_topic: /forward_velocity_controller/commands # Publish outgoing commands here
      # What type of topic does your robot driver expect?
      # Currently supported are std_msgs/Float64MultiArray or trajectory_msgs/JointTrajectory
      command_out_type: std_msgs/Float64MultiArray
      # What to publish? Can save some bandwidth as most robots only require positions or velocities
      publish_joint_positions: false
      publish_joint_velocities: true
      publish_joint_accelerations: false
      joint_topic: /joint_states

      ## Plugins for smoothing outgoing commands
      use_smoothing: true
      smoothing_filter_plugin_name: "online_signal_smoothing::ButterworthFilterPlugin"

      ## Collision checking for the entire robot body
      check_collisions: true
      self_collision_proximity_threshold: 0.01 # Start decelerating when a self-collision is this far [m]
      scene_collision_proximity_threshold: 0.02 # Start decelerating when a scene collision is this far [m]
      collision_check_rate: 5.0 # [Hz] Collision-checking can easily bog down a CPU if done too often.
      lower_singularity_threshold:  100.0  # Start decelerating when the condition number hits this (close to singularity)
      hard_stop_singularity_threshold: 200.0 # Stop when the condition number hits this

      ## Configure handling of singularities and joint limits
      joint_limit_margins: [0.1] # added as a buffer to joint limits [radians]. If moving quickly, make this larger.
